[package]
name = "humentity"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
#ahash = { workspace = true }
#bevy = { workspace = true }
#smallvec = { workspace = true }
bevy = { version = ">=0.17.2", features = ["dynamic_linking"] }
smallvec = { version = ">=1.15.1" }
ahash = { version = ">=0.8.12", features = ["serde"] }
bevy_obj = { git = "https://github.com/AmionSky/bevy_obj/", branch="change-init" }
bytemuck = "1.24.0"
gltf = "1.4.1"
rand = "0.8.5"
serde = "1.0.228"
serde_json = "1.0.145"
walkdir = "2.5.0"
avian3d = { version = ">=0.4.0" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
