[package]
name = "humentity"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
ahash = { workspace = true }
bevy = { workspace = true }
smallvec = { workspace = true }
bevy_obj = { path = "../bevy_obj" }
bytemuck = "1.24.0"
gltf = "1.4.1"
rand = "0.8.5"
serde = "1.0.228"
serde_json = "1.0.145"
walkdir = "2.5.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
