[package]
name = "humentity"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = { version = ">=0.8.12", features = ["serde"] }
bevy = ">=0.18.0"
serde = ">=1.0.228"
walkdir = ">=2.5.0"
bevy_mod_physx = { optional = true, workspace = true }
serde_json = ">=1.0.145"
bytemuck = ">=1.24.0"
gltf = ">=1.4.1"
bevy_obj = ">=0.17.1"
crossbeam-channel = ">=0.5.15"
thiserror = ">=2.0"

[dev-dependencies]
bevy = { version = ">=0.18.0", features = ["experimental_bevy_feathers"] }
toml = ">=0.9.11"

[[example]]
name = "ragdoll"
required-features = ["physics"]

[[example]]
name = "character_creator"
required-features = ["experimental_bevy_feathers"]

[features]
default = []
debug = ["bevy/debug"]
physics = ["dep:bevy_mod_physx"]
experimental_bevy_feathers = ["bevy/experimental_bevy_feathers"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
all = "deny"
missing_const_for_fn = "deny"
or_fun_call = "deny"
get_first = "deny"
redundant_clone = "deny"
manual_ok_or = "deny"
unnecessary_wraps = "deny"
needless_collect = "deny"
get_unwrap = "deny"
manual_while_let_some = "deny"
panicking_unwrap = "deny"
unnecessary_unwrap = "deny"
unnecessary_literal_unwrap = "deny"
unwrap_in_result = "deny"
too_many_arguments = {level = "allow", priority = 16 }
type_complexity = {level = "allow", priority = 10 }

[lints.rust]
nonstandard-style = "deny"
future-incompatible = "deny"
non_local_definitions = "deny"
